
spring:
  application:
    name: qban-fardo-express
  datasource:
    url: jdbc:postgresql://localhost:5432/qban-fardo-express
    username: password
    password: postgres
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: validate
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

# Tema (por default es el tema de saga, tema oscuro es vela)
joinfaces:
  primefaces:
    theme: saga
