
spring:
  application:
    name: qban-fardo-express
  datasource:
#    url: jdbc:mysql://localhost:3306/db_springboot_security_jsf?createDatabaseIfNotExist=true
#    username: root
#    password: password
#    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      database-platform: PostgreSQLDialect #PostgreSQL82Dialect #org.hibernate.dialect.MySQL8Dialect

# Tema (por default es el tema de saga, tema oscuro es vela)
joinfaces:
  primefaces:
    theme: saga
