
spring:
  application:
    name: qban-fardo-express
  datasource:
    url: ${APP_DATASOURCE_URL}
    username: ${APP_DATASOURCE_USERNAME}
    password: ${APP_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: validate
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    properties:
      hibernate:
        default_schema: ${APP_DATASOURCE_SCHEMA}


joinfaces:
  primefaces:
    theme: saga
