
spring:
  application:
    name: qban-fardo-express
  datasource:
    url: jdbc:postgresql://localhost:5432/qban-fardo-express
    username: postgres
    password: mypassword
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: validate
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect


joinfaces:
  primefaces:
    theme: saga
